# Generated by Django 4.2.7 on 2023-12-29 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='acccess_token',
            new_name='access_token',
        ),
    ]
