# Generated by Django 4.2.7 on 2024-01-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_voteprevious'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='refresh_token',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
