# Generated by Django 4.2.7 on 2023-12-31 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_current_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='votes_to_previous',
            field=models.IntegerField(default=1),
        ),
    ]
